spring:
  liquibase:
    change-log: 'classpath:db/dbchanges.xml'
  datasource:
    driverClassName: org.h2.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
  jackson:
    default-property-inclusion: non_null
  mvc:
    format:
      date-time: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
      date: yyyy-MM-dd
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

server:
  port: 8080

demo:
  security:
    jwt:
      password: 'g4kg5D%(;Hd7$?Is&}p:bN!=U33n2)Z'
      expiration-time: 3600

logging:
  level:
    org.hibernate.SQL: ERROR
    com.avlis.pedidoson: trace
